apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hoshi-ui
  namespace: hoshi-note
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`hoshi-note.ixk.me`)
      services:
        - name: hoshi-ui
          namespace: hoshi-note
          port: 80
